### ISSUE TITLE
Cannot receive LN due to timeout exception

### ISSUE THREAD

**Issue by mjdNjhNJ** [ACINQ/phoenix#523]
Recipient is unable to retrieve LN as every attempt ends with "Recipient is not reachable, or does not have enough liquidity" on the sender's device. Automatic channel creation fee is set above the estimated fee for the transaction.

**Logs**
`2024-02-28 15:46:20,638 WARN  f.a.lightning.io.Peer  - TCP connect: Timed out waiting for 1000 ms: 
    remoteNodeId: [REMOVED]fkotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 1000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:191)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:159)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)`

Phoenix 2.2.0
GrapheneOS 2024022600
Pixel 7a

**Comment by dpad85** [comment]
Make sure the recipient app [stays in the foreground](https://phoenix.acinq.co/faq#receiving-or-sending-payments-keeps-failing-what-can-i-do) (otherwise may be disconnected by the OS when in the background). If using Tor, consider disabling it.

Closing this ticket, contact phoenix@acinq.co for support if needed.
