### ISSUE TITLE
debugging bolt12 decoded

### ISSUE THREAD

**Issue by st3b1t** [ACINQ/phoenix#583]
hi,

I tryng to decode the Pheonix **Bolt12** address generated.. but using the Rusty's python bolt12 module:
https://github.com/rustyrussell/bolt12/blob/master/python/examples/decode_offer.py

I wanted to ask how I can correct these errors or use other tools internal to this repository to debug the addresses generated by Phoenix

this seems to generate errors for field differences, genrate this errs:
```bash

$ ./decode_offer.py lno1zrxq8pjw7qjlm68mtp7e3yvxee4y5xrgjhhyf2fxhlphpckrvevh50u0qdh33mzke8ue0k04puq87aq676dwty0m3yd5lua2yeaxsvlrpfscyqszu47nkqymus7crju2anthyqu5ln46var4qs0pnhexzq76e30hm20qqvmyy3x78c9halzxjr45sq756sf57q9708qvdfm8famxn9a3rtvxxvj6ym7dw3ryfjggvtpr6qzgv5y4uul7q2zrw8uj7f59rfnkelq5hkq07wtv54lnhl5kmf6sjyln0khpka4dkqqs60d9rlk4qsz0nwcf9zxscpt7lu
Traceback (most recent call last):
  File "/home/st3b1t/bolt12/rustyrussell-bolt12/python/examples/./decode_offer.py", line 21, in <module>
    offer, whynot = d.result()
  File "/home/st3b1t/.local/lib/python3.10/site-packages/bolt12/bolt12.py", line 559, in result
    ret = Bolt12.decode(hrp, bytestr)
  File "/home/st3b1t/.local/lib/python3.10/site-packages/bolt12/bolt12.py", line 305, in decode
    return Offer(bytestr)
  File "/home/st3b1t/.local/lib/python3.10/site-packages/bolt12/bolt12.py", line 436, in __init__
    super().__init__('lno', tlv_offer, bytestr)
  File "/home/st3b1t/.local/lib/python3.10/site-packages/bolt12/bolt12.py", line 293, in __init__
    self.values, self.unknowns = helper_fromwire_tlv(tlv_table, bytestr)
  File "/home/st3b1t/.local/lib/python3.10/site-packages/bolt12/bolt12.py", line 50, in helper_fromwire_tlv
    tlvs[name], tlv_bytes = fromwire(tlv_bytes)
  File "/home/st3b1t/.local/lib/python3.10/site-packages/bolt12/generated.py", line 257, in fromwire_offer_paths
    val, buffer = fromwire_blinded_path(buffer)
  File "/home/st3b1t/.local/lib/python3.10/site-packages/bolt12/generated.py", line 1464, in fromwire_blinded_path
    while i < lenfield_num_hops:
TypeError: '<' not supported between instances of 'int' and 'tuple'
```

**Comment by dpad85** [comment]
You can use the [`decodeoffer`](https://phoenix.acinq.co/server/api#decode-offer) API call in https://github.com/ACINQ/phoenixd to parse an offer.

Regarding the error you get in c-lightning, we can't help with that. You should report that to Rusty.
